// Store the top 5 watched exercises in the redux store
export const GET_EXERCISE_DATA = 'GET_EXERCISE_DATA';
export const GET_EXERCISE_DATA_SUCCESS = 'GET_EXERCISE_DATA_SUCCESS';
export const GET_EXERCISE_DATA_FAILURE = 'GET_EXERCISE_DATA_FAILURE';

export const SET_EXERCISE_DATA = 'SET_EXERCISE_DATA';
export const SET_EXERCISE_DATA_SUCCESS = 'SET_EXERCISE_DATA_SUCCESS';
export const SET_EXERCISE_DATA_FAILURE = 'SET_EXERCISE_DATA_FAILURE';

export const SET_SOUND_DATA = 'SET_SOUND_DATA';
export const SET_SOUND_DATA_SUCCESS = 'SET_SOUND_DATA_SUCCESS';
export const SET_SOUND_DATA_FAULIRE = 'SET_SOUND_DATA_FAILURE';

export const SET_PAUSE_TIME = 'SET_PAUSE_TIME';
export const SET_PAUSE_TIME_SUCCESS = 'SET_PAUSE_TIME_SUCCESS';
export const SET_PAUSE_TIME_FAILURE = 'SET_PAUSE_TIME_FAILURE';

export const SET_BREAK_TIME = 'SET_BREAK_TIME';
export const SET_BREAK_TIME_SUCCESS = 'SET_BREAK_TIME_SUCCESS';
export const SET_BREAK_TIME_FAILURE = 'SET_BREAK_TIME_FAILURE';

export const SET_SUBCATEGORY_DATA = 'SET_SUBCATEGORY_DATA';
export const SET_SUBCATEGORY_DATA_SUCCESS = 'SET_SUBCATEGORY_DATA_SUCCESS';
export const SET_SUBCATEGORY_DATA_FAILURE = 'SET_SUBCATEGORY_DATA_FAILURE';

export const SET_USER_DATA = 'SET_USER_DATE';
export const SET_USER_DATA_SUCCESS = 'SET_USER_DATE_SUCCESS';
export const SET_USER_DATA_FAILURE = 'SET_USER_DATE_FAILURE';